{
 "title": "Otter monitor",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Otter节点存活状态监控",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "otter_up", "legendFormat": "{{role}}" }
   ]
  },
  {
   "title": "Otter Pipeline同步延迟监控",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "pipeline_delay_time", "legendFormat": "Pipeline: {{Pipeline}}" }
   ]
  },
  {
   "title": "Otter Pipeline最后采集时间监控",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "pipeline_last_coll_time", "legendFormat": "Pipeline: {{Pipeline}}" }
   ]
  }
 ]
}